[[nodes]]
id = "2"
type = "encounter"
text = """
これはテストデータです
アークデーモンが現れた
"""
    [[nodes.enemies]]
    Name = "アークデーモンA"
    HP = 10
    CS = 5
    [[nodes.enemies]]
    Name = "アークデーモンB"
    HP = 10
    CS = 5
    [[node.outcomes]]
    condition = "combat_won"
    next_node_id = "5"
    [[node.outcomes]]
    condition = "combat_lost"
    next_node_id = "game_over"