[[nodes]]
id = "start_node"
type = "story"
text = "あなたは森の入り口に立っています。"

[[nodes.choices]]
text = "森の中へ進む"
next_node_id = "forest_path"

[[nodes.choices]]
text = "引き返す"
next_node_id = "village_entrance"

[[nodes]]
id = "forest_path"
type = "encounter"
text = "突然、オークが現れた！"

[nodes.encounter]
type = "combat"
combat_system_type = "DnD5e"

[nodes.encounter.combat_data]
terrain = "forest"
difficulty = "medium"

[[nodes.encounter.combat_data.enemies]]
name = "Orc"

[nodes.encounter.combat_data.enemies.stats]
hp = 15
ac = 13

[[nodes.outcomes]]
condition = "combat_won"
next_node_id = "clearing"

[[nodes.outcomes]]
condition = "combat_lost"
next_node_id = "game_over"