system = "lonewolf"


[Tables]
SkillTable = ["Camouflage", "Hunting", "SixthSense", "Tracking","Healing",
 "Weaponskill","Mindshield", "Mindblast", "AnimalKinship", "MindOverMatter"]
WeaponSkillTable = { 0 = "Dagger", 1 = "Spear", 2 = "Mace", 3 = "Shortsword", 4 = "Warhammer", 5 = "Sword", 6 = "Axe", 7 = "Sword", 8 = "Quaterstaff", 9 = "Broadsword"}
FirstEquipmentTable = {0 = "Broadsword", 1 = "Sword", 2 = "Helmet", 3 = "Meal", 4 = "ChainmailWaistcoat", 5 = "Mace", 6 = "HealingPotion", 7 = "Quatertaff", 8 = "Spear", 9 = "Gold"}

    [[Tables.Armors]]
    Name = "ChainmainWaistcoat"
    Slot = "Body"
    Hpbonus = 2

    [[Tables.Armors]]
    Name = "Helmet"
    Slot = "Head"
    Hpbonus = 2

[[nodes]]
id = "1"
type = "story"
text = """
これはテストデータです
テキストも仮のものです
"""
    [[nodes.choices]]
    description = "If you wish to use your Kai Discipline of Sixth Sense, turn to 2."
    next_node_id = "2"
    required_discipline = "SixthSense"

    [[nodes.choices]]
    description = "If you wish to take the right path into the wood, turn to 3."
    next_node_id = "3"
    required_item = "SilverKey"

    [[nodes.choices]]
    description = "If you wish to follow the left track, turn to 4."
    next_node_id = "4"

[[nodes]]
id = "2"
type = "encounter"
text = """
これはテストデータです
アークデーモンが現れた
"""
    [[nodes.enemies]]
    Name = "アークデーモンA"
    HP = 10
    CS = 5
    [[nodes.enemies]]
    Name = "アークデーモンB"
    HP = 10
    CS = 5
    [[node.outcomes]]
    condition = "combat_won"
    next_node_id = "5"
    [[node.outcomes]]
    condition = "combat_lost"
    next_node_id = "game_over"

[[nodes]]
id = "3"
type = "random_roll"
text = "1-5なら6へ　6-0なら7へ"
    [[nodes.outcomes]]
    description = "1-5なので6へ"
    condition_int = [1,2,3,4,5]
    next_node_id = "6"
    [[nodes.outcomes]]
    description = "6-0なので7へ"
    condition_int = [6,7,8,9,0]
    next_node_id = "7"


[[nodes]]
id = "game_over"
type = "end"
text = "ゲームオーバー。あなたの旅はここで終わりました。"